◯ numpy基礎

In [1]:
import numpy

a = numpy.array([1, 2, 3])

In [2]:
a

array([1, 2, 3])

In [4]:
a.shape

(3,)

In [5]:
b = numpy.array([[1, 2, 3], [4, 5, 6]])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b.shape

(2, 3)

In [8]:
numpy.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
numpy.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
numpy.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
numpy.random.random((3,3))

array([[0.8784095 , 0.55501384, 0.92349283],
       [0.69853597, 0.1074227 , 0.94005221],
       [0.66591329, 0.71042352, 0.1356606 ]])

In [13]:
a = numpy.array([[1, 2, 3], [4, 5, 6]])
b = numpy.array([[7, 8, 9], [10, 11, 12]])

In [14]:
a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [15]:
a * b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [16]:
numpy.dot(a, b.T)

array([[ 50,  68],
       [122, 167]])